### ISSUE TITLE
Spectrum hashing

### ISSUE THREAD

**Issue by kiahmcintosh** [matchms/matchms#106]
Currently `hash(spectrum)` for a Spectrum object gives an unhashable type error. Could a hash function be added?

**Comment by sverhoeven** [comment]
Just out of curiosity, for what are you using the hash function?

**Comment by kiahmcintosh** [comment]
I am doing molecular networking using the NetworkX package. NetworkX uses dictionaries to store the data so nodes in the network are required to be hashable.

**Comment by florian-huber** [comment]
@sverhoeven what would you use to hash?
Only issue I see is that we have no default ID for the Spectrum object and it will rely on what metadata is parsed.
Could it be something like:
```python
class Spectrum: 

...

    def __hash__(self):
        return hash(self._metadata.get("spectrumid", "no spectrumid"))
```

**Comment by sverhoeven** [comment]
By only using id, a filtered Spectrum would have the same hash as unfiltered, while their content is different. Using a hash based on id might be OK if you don't have same identifier in a set or as dict keys.

When you don't have an id fallback to use all data of Spectrum. This could be done by giving JSON string to hash(). It will be very slow to generate so cache the hash so it does not have to be recalculated each time and unset it during clone().

**Comment by florian-huber** [comment]
For the GNPS data we worked with, the ``spectrumid`` field was unique. But it is not standard for all the other import formats.
And all other field can also undergo changes during filtering/processing (e.g. title/name changes etc.).

We hence might have to add a better, more standardized ID field to the spectrum objects. 
Maybe this might even need a method that sees all spectrums?
For instance along those lines:
```python
add_id_to_spectrums(spectrums, default_id="spectrumid"):
    for i, spectrum in enumerate(spectrums):
        if spectrum.get(default_id):
            assert spectrum.get(default_id) not in ids_dict.keys(), "Non-unique identifier found."
            ids_dict[i] = spectrum.get(default_id)
        else:
            spectrum.set(default_id, str(i))
```
Just using the counter as id seems a bit poor, but I am no so sure we can find one standard field that does it well enough...

**Comment by florian-huber** [comment]
In #10 @sdrogers pointed to SPLASH which sounds like a good solution for the spectrum hashing!
--> https://github.com/berlinguyinca/spectra-hash/blob/master/python/splash/splash.py

Not a pypi or conda package, but the actual needed code is just a few lines which could be added to matchms.

**Comment by florian-huber** [comment]
@sdrogers how commonly used is SLASH as a unique spectrum identifier?
The reason I am asking: if it is not super common, then it would in our case be enough to only use the hash for the mz-intensity pairs of the spectrum.

In the original SPLASH method combines four different blocks: one for the spectrum-type (MS, UV, Raman...), two that I didn't immedeately get about the spectrum histogram, and finally one which is a has based on all the ions (mz: intensity). 
Seems to me, like the last block is all we need.

**Comment by sdrogers** [comment]
I don’t know how much it’s used. However, my opinion would be to use all of it simply because it’s more standard than only using the last bit.

also, perhaps one reason it’s not widely used is because it isn’t in packages like matchms :-)

**Comment by florian-huber** [comment]
I ran some SLASH code and tested how easily we could implement part of it in matchms (#259... still only playing around).

Some isses I have with simply using SPLASH as it is:
- It uses quite a list of parameters (which makes me wonder how reproducible exact hashes really are)
- At least one if its parameters seems not well chosen for many matchms-related use cases. The intensity precision is set to 0 which means that 0 decimals will be taken into account. Since we often scale intensities to [0, 1] that means that all differences in intensity won't end up in the final hash.
- it is not a pypi/conda package (could be installed as github repo, though)
- their hash is a string, which is fine, but won't work with Python to replace the `__hash__` method which wants an integer.

So, I would suggest the following (fully up for discussion):
### Implement two different hashes as part of the matchms.Spectrum class:
- metadata_hash --> generates a hash from the metadata (e.g. in json form), could optionally also just look at a few fields if that sounds better.
- spectrum_hash --> generates a hash based on peaks (list of mz: intensity pairs as done in the last block of SPLASH).
I imagine that could have a few nice use cases: metadata_hashes will change if information is changed during processing (e.g. added inchikey etc.) and the spectrum_hash will change if peaks are scaled or filtered.

Taken together the __hash__ method could use both so that each matchms `Spectrum` will have a unique hash (e.g. `int_from_bytes(metadata_hash + spectrum_hash)`. That is then also what people would get if they run `hash(Spectrum)`.

**Comment by hechth** [comment]
@florian-huber This sounds good and being able to separate the peak hash and metadata hash could be very useful.

**Comment by florian-huber** [comment]
With #259 `Spectrum()`objects now have hashes.
