### ISSUE TITLE
Currently it is not clear how users should query the scores

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#152]
In our simple code examples we use something like ``for (reference, query, score, n_matching) in scores:``

For most real-life applications this is not very feasible because scores will be a *huge* matrix!
We should either provide a better way to query the scores (which I would prefer), or change or comment the code examples.

**Comment by sverhoeven** [comment]
There are the `scores_by_query(query)` and `scores_by_reference(reference)` methods on Scores class. 

What other way do you propose? A method to filter scores that returns a sparse matrix?

**Comment by florian-huber** [comment]
I am not yet entirely sure.
What I certainly would like to add is:
- provide additional code examples (and/or update the current ones) that use `scores_by_query(query)` and `scores_by_reference(reference)`

In addition, it seems that a very common function/method that users may want is to return the top-*n* scores(+candidates) for every query. In principle that is not overly complicated and can be done using numpy functions (e.g. on top of the `scores_by...` method). But it still might not be straightforward to all users, which would make it a nice additional functionality.
I guess we should not include something like this as a method of `Scores`, but rather provide a separate function for it, say `return_top_scores` or `find_best_matches`.
Or what do you think?

**Comment by sverhoeven** [comment]
Before due to unknown return of the similarity functions we had to pass in a lambda to use the Scores class to perform sorting.
Now that we are using BaseSimilarity class, we could add a order/sort method to it so that we can do the top-n . So only similarity functions which return more than a single number will need to override it.

**Comment by florian-huber** [comment]
That sounds good to me!
Because as you said, in the only current code example we provide for `scores_by_query` we used a lambda function. That does the job, but usually numpy `argsort` or similar functions are much faster. Making those choices for the user by implementing a sort method would be really nice I think.

My first impulse would be to add a method on top of the current methods, e.g. `scores_by_query(query, sorted="False"/"ascending"/"descending")`?
But we could also implement an additional, separate method to `Scores`.

**Comment by sverhoeven** [comment]
Which direction (ascending/descending) of the sort depends on the similarity function, so I would not add it as an argument. Just use the direction that the `BaseSimilarity.order(spectrums, similarities)` method implements. Or are you sometimes interested in the worst scoring pairs?

I would like to see `Scores.top_scores_by_query(query, n=np.Inf)` and `Scores.top_scores_by_reference(reference, n=np.Inf)`.  As having a lot of arguments (spectrum, sorted=False, top=np.Inf) and their defaults is a higher mental load than having more methods. Also boolean arguments are hard to understand, eg. what happens if sorted=False.

I can also imagine that a user would like to get the top 5 (or scores above some threshold) references for each query. Something like `Scores.top_n_scores(n=np.Inf)` and `Scores.top_filtered_scores(filter=lambda x: x > 0.55 )`.

**Comment by florian-huber** [comment]
OK, I see. I first was confused by implementing the `.order()` or `.sort()` method as part of the similarity score class. But thinking of different score types it makes sense to do that.
The functions you suggest look good to me as well. I would still add an 'ordered' option to the `scores_by_...` methods because it looks like an easy, simple addition to me. So then we would have:
- `Scores.scores_by_query(query, 'sorted'=False)`
- `Scores.scores_by_reference(reference, 'sorted'=False)`
- `Scores.top_scores_by_query(query, n=np.Inf)`
- `Scores.top_scores_by_reference(reference, n=np.Inf)`

**Comment by florian-huber** [comment]
There is still no implementation of:
- `Scores.top_scores_by_query(query, n=np.Inf)`
- `Scores.top_scores_by_reference(reference, n=np.Inf)`
But sorting has now been added in PR #153, so I will close this issue. Should further functionality be necessary then better restart with a new, fresh issue.
