### ISSUE TITLE
precursor_mz of 0.0 raises error 

### ISSUE THREAD

**Issue by niekdejonge** [matchms/matchms#189]
On line 94 of ModifiedCosine.py the following assert statement gives a problem:
assert reference.get("precursor_mz") and query.get("precursor_mz"), message

When precursor_mz is specified but it is 0.0 it will raise an error (since assert 0.0 raises an error). 

The error is not really that this raises an error, but the fact that precursor_mz can have a value of 0.0, while this is not actually possible. 

Suggested solutions:
In add_precursor_mz.py add a check to remove the spectrum if precursor_mz and pepmass are 0.0.
or change assert function in ModifierCosine.py so it does not raise an error when precursor_mz is 0.0, but only when it is not available.

**Comment by florian-huber** [comment]
Thanks for starting this issue Niek!
We should indeed not allow a precursor_mz of 0.0. We could add an `assert  precursor_mz > 0` since also negative values should not be allowed.

However, I would not remove the spectrum in that function. We tried to have filters only do what the name suggests, so it would be better to add a separate filter like `require_precursor_mz` (see the other `require....` filters).
This is also, because GC-MS spectra do not have a precursor-m/z, so we removing spectra without this field should remain optional.

@niekdejonge would you be up to start a PR on this?

**Comment by niekdejonge** [comment]
Yes, I will! 
I do not have rights for matchms yet, could you add me to matchms?

**Comment by florian-huber** [comment]
Great!
(just also gave you rights)

**Comment by niekdejonge** [comment]
solved with #191
