### ISSUE TITLE
Filtering out spectra

### ISSUE THREAD

**Issue by Adafede** [matchms/matchms#199]
**My feature is a request**
I saw no straightforward solution to filter out bad spectra from a list of spectra.

**I would like to be able to filter spectra themself (not the peaks or metadata) depending on rules I establish**
Something like discarding spectra which precursor mass is .000 or .500, where the precursor mass is outside a 10ppm range of the known formula, etc.
I am currently doing it *outside* matchms and it is quite painful.

**Any good starting points?**
Generate a list of IDs corresponding to the given criteria and filter spectrum list that way?
Having those ID as scan IDs would also be great.

**Additional context**
I am currently filtering the big GNPS dataset to create decoys.
Working with mzml instead of mgf would be probably way faster.

**Comment by florian-huber** [comment]
Many thanks @Adafede for starting this issue.
I think more such filters would indeed be a nice addition to matchms.
Based on the current matchms API, this sounds like adding new `require_...` filters.
Right now matchms has
- `require_minimum_number_of_peaks`
- `require_minimum_of_high_peaks`
- `require_precursor_below_mz`
- `require_precursor_mz`

Here a few questions from my side to understand things a bit better:

### Handling nonsense precursor-m/z entries

> discarding spectra which precursor mass is .000 or .500

--> Do I get it right: you have spectra with nonsense entries such as `precursor_mz=.000` ?  
If so, I think we could add this to `require_precursor_mz`. Did you encounter other such examples besides .000 or .500 ?

### Handling precursor-m/z entries which don't fit other metadata information (e.g. formula)

> precursor mass is outside a 10ppm range of the known formula

That could be a bit more complicated.
In principle we could easily add a filter like `require_precursor_mz_formula_match` or something like that. But that only works if we can rely on several metadata entries: the charge/adduct, the formula, and the precursor-m/z. Because we would actually have to compare an estimated `estimated parent mass` with the formula-based mass (I guess that is what you are after, right?). 
So, it might rather be a `require_parent_mass_formula_match` I guess.

### More examples?

You gave the two use-cases above. Do you have any other in mind that you would frequently need to discard spectra?

### .mgf versus .mzml

Currently matchms can import both mgf and mzml files, but we are missing and mzml exporting function. I think that should be addressed soonish --> #201

I guess though, that both file formats are now ideal if it comes to speed.
If memory issues are a problem, you could make use of the fact that the importing functions are Python generators, so you discard spectra that don't match your criteria, e.g.

```python
from matchms.filtering import add_parent_mass
from matchms.filtering import default_filters
from matchms.filtering import normalize_intensities
from matchms.filtering import require_minimum_number_of_peaks, require_precursor_mz
from matchms.filtering import select_by_mz
from matchms.filtering import select_by_relative_intensity
from matchms.importing import load_from_mgf


def test_user_workflow():

    def apply_my_filters(s):
        s = default_filters(s)
        s = add_parent_mass(s)
        s = normalize_intensities(s)
        s = select_by_relative_intensity(s, intensity_from=0.0, intensity_to=1.0)
        s = select_by_mz(s, mz_from=0, mz_to=1000)
        # Remove unfit spectrums
        s = require_minimum_number_of_peaks(s, n_required=5)  # s becomes None if criteria is not met
        s = require_precursor_mz(s)  # s becomes None if criteria is not met
        return s

    spectrums_file = "... filename here ... "

    # apply my filters to the data
    spectrums = [apply_my_filters(s) for s in load_from_mgf(spectrums_file) if apply_my_filters(s) is not None]
```

**Comment by Adafede** [comment]
Hi @florian-huber, thank you for handling issues so well!

1. _non-sense precursor entries_: **Yes absolutely you get it right**. Of course, they are not coming from my runs but from GNPS spectral library (you might have already spotted them). (There is not only .000 and .500 but also .00, .50, and so on. Actually, I filter them out by doing (in R) : `  filter((100 * precursor) %% 50 != 0)`
2. _unmatched MF formulas_: I perfectly understand it is more difficult. Again, it is to filter out "bad" entries from GNPS spectral library. I am evaluating my annotation methods on it so of course, let's say having a spectrum with 50ppm deviation might be quite challenging to annotate depending on the tool you are using. Therefore, being able to filter them at 5, 10 ppm would be great. Of course, this application case is quite restricted and I perfectly see it as non-urgent.
3. _more examples_: Not I could think of at the moment... a lot is already implemented 👍🏼 
4. _mg vs mzml_: Very nice to know!

I also wanted to ask about networks but it looks like #196 is already on the way... :) I think many people will like the direction your packages are going! Congrats

**Comment by florian-huber** [comment]
Thanks for elaborating!
(and special thanks for the positive feedback of course 😃)

I made two new issues from this -> #206 and #207 (as well as #201 for expanding the `.mzml` options).
So I would close this issue for now (feel free to re-open if needed).
