### ISSUE TITLE
Move functions for peak matching / pair detection before score calculation out of Similarity classes to separate file

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#210]
**Describe the bug**
The [methods](https://github.com/matchms/matchms/blob/5cf15bcc89128f1bffacd62a8688062edfd8d06e/matchms/similarity/CosineHungarian.py#L69-96) to determine which pairs are matched & scored with a similarity metric partially reside in the Similarity metric classes (see `CosineHungarian`) while their functionality is actually useful for other classes and similarity scores as well.

**Expected behavior**
Methods which can be decoupled from a class should move to a separate file, dedicated to match pairs of 2 spectra before similarity score computation.

**Additional context**
This could be achieved by moving the functions to a specific file (or spectrum_similarity_functions.py as of now) OR by extending the functionality in a similar way to the similarity metrics - by using a basic `Matching` class, which can be greedy, match all peaks with a given tolerance, choose the one which fit's with a given score, extracts k best matches etc.

**Comment by sdrogers** [comment]
Will it be possible to completely decouple this?

Finding all matching peak pairs could be decoupled, but that’s only a small step in the process. To choose a particular subset of these (greedy, Hungarian) is only possible with a particular score.

**Comment by florian-huber** [comment]
The method you refer to is part of `CosineHungarian` which we mostly used as a reference method to inspect the faster `CosineGreedy` implementation. So far we only needed the mentioned functions (`get_matching_pairs_matrix()`) for this one implementation, so that's why it still is in the class itself.

I would be fine with moving those functions to `spectrum_similariy_functions.py`, in particular if there might be other use-cases for them elsewhere. That is also easy to do and won't cost us much time.
Designing/building a new Matching class, however, sounds like much more work and I am not even sure it would work because we optimized the CosineGreedy quite a bit to make it faster. As a result the implementations differ a lot. 

The step of collecting the pairs is [already a shared function](https://github.com/matchms/matchms/blob/5cf15bcc89128f1bffacd62a8688062edfd8d06e/matchms/similarity/spectrum_similarity_functions.py#L9y).
