### ISSUE TITLE
Return spectrum similarity score as pair or single value instead of matrix

### ISSUE THREAD

**Issue by chetankm1992** [matchms/matchms#247]
When computed similarity score by using following code:
`scores = calculate_scores(spectrums, spectrums, spec2vec_similarity,
                          is_symmetric=True)`
it gives memory error or requires a very large memory when you have very large number of spectrums (e.g., more than 41262 or around 55039). Because it can not fit NxN array when it is very big in size. The solution to this can be to return the score as pair (spectrum1, spectrum2, score) or may be just the score and it may not give memory issue.
To do this, I checked the calculate_score function and other corresponding function but did not find where spec2vec_similarity score is being computed and if I change NxN array holding scores to a paired array, what other lines of code I have to change. I was wondering if you can help me with this.
Thanks

**Comment by florian-huber** [comment]
Hi @chetankm1992, thanks for the question.

This is something that matchms currently cannot handle properly. 
The reason is that you simply want to store too many scores at once. Since the code you mention will compute scores for all possible pairs this means you get an array of about 50,000 * 50,000 scores. I think that would be about 20GB.

Currently, the only solution is to break it into smaller chunks and then either store them on the hard-disk, or only keep a subset you need and proceed. 
Say, something like:
```python
import numpy as np

chunk_size = 5000
n_chunks = int(np.ceil(len(spectrums)/chunk_size))
for i in range(n_chunks):
    for j in range(i, n_chunks):
        scores = calculate_scores(spectrums[i*chunk_size:(i+1)*chunk_size],
                                  spectrums[j*chunk_size:(j+1)*chunk_size], spec2vec_similarity)
        # then do something with scores, e.g. save them etc....
```
(this dummy code probably won't work straightaway because spectrums might be a list, but you get the idea)

I hope that matchms can at some point deal with such things automatically, for instance by switching to sparse arrays (see other issue: #60). But that will take some more time...

**Comment by florian-huber** [comment]
Out of curiosity: What is your aim with this calculation? Are you -in the end- interested in all scores or only the higher ones? 

If so, keeping only values above a certain threshold could allow creating a more memory-efficient sparse matrix.

**Comment by sdrogers** [comment]
Would it make sense for matchms to return a generator rather than the matrix itself? It can then be iterated through and handled however by the user?

**Comment by florian-huber** [comment]
In principle, using a generator sounds like a good idea. But I foresee that this will be very tricky to implement because of the way the calculations are done. If we would simply loop through all pairs that should work, but we currently get a huge speed gain by first computing all necessary Spec2Vec embeddings (and keeping them in memory). 

I think a hybrid solution could work. By that I mean to still compute all embeddings for all `spectrums` and keep them in memory (for 50,000 spectra that should be something around 100-150MB so that will be fine).  And then use a generator for the score computations...

**Comment by hechth** [comment]
@florian-huber I think this has been adressed with the sparse scores actually if I am not mistaken?

**Comment by florian-huber** [comment]
Outdated, was fixed.
