### ISSUE TITLE
Plot spectra directly after scoring

### ISSUE THREAD

**Issue by jundahuang9123** [matchms/matchms#250]
**Is your feature request related to a problem? Please describe.**
Is there a way to plot spectra when match? Since Score and Spectrum are two different object, I do not find how to trace back easily

**Describe the solution you'd like**
for match in matches:
     if .....:
        spectrum_query.plot()
        spectrum_reference.plot()

**Comment by florian-huber** [comment]
Hi @jundahuang9123 , thanks for opening the issue.
Such a feature doesn't exist in matchms. Mostly because it depends a lot on the context what people would call a match.
In some cases that might simply be a score above a set threshold, but sometimes it has to be a complex combination of things (precursor m/z within a certain range, score > threshold ...).

So you will have to define what you consider a match yourself.
For simple threshold checks it could look like this:
```python
from matchms import calculate_scores
from matchms.similarity import CosineGreedy

scores = calculate_scores(references=spectrums_reference,
                          queries=spectrums_query,
                          similarity_function=CosineGreedy())

threshold_for_match = 0.8

for query in spectrums_query:
    selected_scores = scores.scores_by_query(query, sort=True)
    for score in selected_scores:
        if score[1]["score"] >= threshold_for_match:
            query.plot()
            score[0].plot()
        else:
            break
```

**Comment by jundahuang9123** [comment]
Alright, yes I am aware of the threshold differences per user. So if i'm understand correctly, Score object [0] is the spectrum then?

**Comment by florian-huber** [comment]
Yes, that's correct!

**Comment by jundahuang9123** [comment]
Thank you so much! I got it working now!
