### ISSUE TITLE
Load spectra from already loaded MGF bytes or file-like object

### ISSUE THREAD

**Issue by bernardolk** [matchms/matchms#254]
**Is your feature request related to a problem? Please describe.**
I would like to use a file selector widget to select and upload an MGF file from a user's machine into the application's memory (which is not currently running at the user's machine) and use it with matchms. Having only path to file option for importing the MGF data makes this use-case impossible (without extra steps).

**Describe the solution you'd like**
I would like to use a file selector widget to select and upload a MGF file from a user's machine into memory of the application and then pass that file-like or bytes object to the MGF loader _instead of passing a local path of the MGF file to it_

**Any good starting points?**
I think we would need to modify the MGF object constructor (or parents) to support this

Thanks

**Comment by bernardolk** [comment]
I can implement the changes. Would love to hear your input though before starting :)

**Comment by florian-huber** [comment]
I think I get your point. That would indeed not work with the current importing functions.
I am just not sure (yet) how this would be implemented design-wise.
The importing functions currently work with file/path names so that should remain possible as well to avoid that code of other users breaks.

Two options I see would be:
1) have two different importer functions, one for file-name strings and one for file-like objects 
or 
2) (which I think I would prefer) to add the possibility of passing either a string or an file-like object to the same function. Maybe simply check the input and handle accordingly (`is_file_like = not isinstance(file, str)` or something).

Currently `matchms.importing` contains a number of different functions for different file formats (mgf, json, msp, mzxml...), but there is no parent class. The reason is partly historic and due to the very different ways the different file formats are imported. But depending on how general the implementation of the new functionality is, adding a base importer class could be an elegant solution.

**Comment by bernardolk** [comment]
Thanks for the thorough response. I think I agree with your suggestion number two; I will think about both though and come up with a proposition.
