### ISSUE TITLE
Handling of GCMS spectral match

### ISSUE THREAD

**Issue by oolonek** [matchms/matchms#348]
**Is your feature request related to a problem? Please describe.**

When matching GCMS data (EI fragmentation) no parent mass is present.
Spectral matching can be done using cosine score and a large parent mass tolerance. However this is highly inefficient when querying large spectral databases. 

**Describe the solution you'd like**
It would be nice to have a function similar to PrecursorMzMatch() but that would work on a restricted number of fragment peaks.

e.g FragmentMzMatch(number_of_peaks=N, tolerance=T, tolerance_type="Dalton")

This function could filter the spectral library for all spectra having at least N peaks (or maybe the topN peaks by intensity ?), with a tolerance T in Dalton  matching the query spectrum.

**Additional context**
Found some related PR/discussions here https://github.com/matchms/matchms/pull/151 but I wonder if such filtering has been implemented. Didn't find anything in the doc.

**Comment by hechth** [comment]
Please have a look at the filter functions - those actually already allow filtering in the exact way as you described it.

**Comment by oolonek** [comment]
hi @hechth thanks for the answer. I might not have been clear in my explanation or not understood correctly the filtering functions.
I went here https://matchms.readthedocs.io/en/latest/api/matchms.filtering.html but didn't find a function which could help me implement the following action : 

> Given a query spectrum, filter a spectral library for all spectra having at least N peaks with a tolerance T in Dalton matching the query spectrum.

I see filtering option which would return _modified spectra_ (according to top N peaks, mz range etc) but I dont want a modified spectra. I just want a subset of an ensemble of spectra whose fragments match the one of a query spectra.

Hope it's a bit clearer this way. Happy to develop if needed or look at the filtering function I might have missed.
Thanks !

**Comment by sdrogers** [comment]
Can’t see how this would be faster (in theory at least) than just doing a cosine score, setting the Ms2 mz threshold to the value of tolerance you want, setting min match peaks to your n? It would do the same no? All the spectra with non zero score would be the ones you’re after.

**Comment by oolonek** [comment]
Well I would see the see the FragmentMzMatch() function as a filter so I guess it would render the overall calculation process faster (by just restricting the number of spectra to do the cosine calculation on ...)

Small example with the PrecursorMzMatch() (matching a .mgf of 175 spectra against a NIST MSP of 574826 spectra.)

Parameters : 

```
parent_mz_tol = 0.05
msms_mz_tol = 0.05
min_cos = 0.6
min_peaks = 6
```

Output : 

```
Proceeding to the spectral match ...
100%|██████████| 92218/92218 [00:10<00:00, 8404.15it/s] 
Finished in 14.281208992004395 seconds.
```

If I open the parent_mz_tol

 ```
parent_mz_tol = 10
msms_mz_tol = 0.05
min_cos = 0.6
min_peaks = 6
```

Output : 

```
Proceeding to the spectral match ...
100%|██████████| 3307194/3307194 [04:37<00:00, 11905.20it/s]
Finished in 281.7572441101074 seconds.
```

(Opening to 400 m/z would results in ca. 2 hours calculation apparently)

So I would expect a filtering function working on fragments to work just as quick as the PrecursorMzMatch() function working on the precursor. On the other hand I would also expect that a filtering function applied prior to spectral match should work in any case (given that the output of the filtering function is smaller) faster than a spectral matching function with no filter.

Maybe I am missing a point ...
Thanks you for the feedback.


The code used is the following one : 

```
parent_mz_tol = 400
msms_mz_tol = 0.05
min_cos = 0.6
min_peaks = 6
    

print('Proceeding to the spectral match ...')


# timer is started
start_time = time.time()


from matchms.similarity import PrecursorMzMatch
from matchms import calculate_scores
from matchms.similarity import CosineGreedy

similarity_score = PrecursorMzMatch(tolerance=float(parent_mz_tol), tolerance_type="Dalton")
chunks_query = [spectrums_query[x:x+1000] for x in range(0, len(spectrums_query), 1000)]

for chunk in chunks_query:
    scores = calculate_scores(chunk, spectrums_db_cleaned, similarity_score)
    indices = np.where(np.asarray(scores.scores))
    idx_row, idx_col = indices
    scans_id_map = {}
    i = 0
    for s in chunk:
        scans_id_map[i] = int(s.metadata['scans'])
        i += 1
    cosinegreedy = CosineGreedy(tolerance=float(msms_mz_tol))
    data = []
    for (x,y) in tzip(idx_row,idx_col):
        if x<y:
            msms_score, n_matches = cosinegreedy.pair(chunk[x], spectrums_db_cleaned[y])[()]
            if (msms_score>float(min_cos)) & (n_matches>int(min_peaks)):
                feature_id = scans_id_map[x]
                data.append({'msms_score':msms_score,
                            'matched_peaks':n_matches,
                            'feature_id': feature_id,
                            'reference_id':y + 1,
                            'inchikey': spectrums_db_cleaned[y].get("name")})
    df = pd.DataFrame(data)
    # df.to_csv(output_file_path, mode='a', header=not os.path.exists(output_file_path), sep = '\t')

print('Finished in %s seconds.' % (time.time() - start_time))
```

**Comment by sdrogers** [comment]
My point is that finding the fragments that match _is_ basically the main step in computing cosine similarity. So having a filter to find the ones that match and then calculating cosine as a separate step would actually be less efficient.

ie in the cosine greedy method, step one is finding all the fragment pairs from spec 1 and spec 2 that are within some tolerance and then only gives a non-zero score if the number of such matches exceeds a threshold. This, if I understand correctly, is what you want your filter to do?

**Comment by florian-huber** [comment]
If I understand the discussion correctly, @sdrogers is right, the CosineGreedy will mostly do just that: detect matching peaks (within tolerance) and then multiple the intensities. So the matching is already done by the score.

If you would like to remove spectra with < 10 peaks beforehand, then matchms has the filter function `require_minimum_number_of_peaks`.
```python
from matchms.filtering import require_minimum_number_of_peaks

spectrums = [require_minimum_number_of_peak(s, n_required=10) for s in spectrums]
```

**Comment by sdrogers** [comment]
Not sure that filter is the right one -- I think the request is for all
spectra that have at least N peaks within some tolerance of the query
spectrum.

A couple of further points...
1. Notwithstanding that I don't think it would make the overall process
faster, a fragment match filter would not be as quick as a precursor match,
simply because there are loads of fragments to check, and only one
precursor.
2. The statement "all spectra having at least N peaks (or maybe the topN
peaks by intensity ?), with a tolerance T in Dalton matching the query
spectrum" is a little ambiguous as the relationship between peaks isn't
always 1-1. I.e. (and this is obviously a silly case, but makes the point).
What if a DB spectrum has N peaks within the tolerance T of a single peak
in the query? I guess you wouldn't want to keep it.

The way the matching is done for cosine similarity is a good way of
overcoming that problem...

The MS2 matching in cosine similarity first finds all pairs (one from each
spec) that are within the tolerance (note that any particular peak could
appear in more than one pair). It then sorts these pairs by their intensity
product (descending), And iterates through the pairs, adding a pair to the
score if neither peak appears in a pair that has been used before:

https://github.com/matchms/matchms/blob/e780a91f9dfb7ba975f0e8e2732f800ee122163f/matchms/similarity/spectrum_similarity_functions.py#L89-L110

This method returns (as well as the score), the number of matching pairs
used in the similarity calculation. I think there's a strong argument that
this is the best definition of number of matching peaks to use (it's the
actual number that you can use to calculate the score). In my slightly odd
example above, there would only be one matching pair used as the peak from
the query can only be used once.

Hope this clears things up a bit. Basically, "number of matching pairs"
isn't quite as easy to define as might first appear and cosine has a good
way of computing one definition of it. This is essentially the main
processing bottleneck of cosine calculation, so extracting it and
performing it as a pre-processing step isn't going to save any time.

Of course, alternative "number of matching pairs" definitions exist, and if
you want one of those, then a filter might be the best bet. *However*, it
would seem odd to me to define it differently for filtering and similarity
calculation.

**Comment by florian-huber** [comment]
> the request is for all
spectra that have at least N peaks within some tolerance of the query
spectrum.

Yes, you're right. I just thought that it won't hurt to run the other filter first, because if you would require >= 10 peaks to match one could savely ignore all spectra with < 10 peaks as a first step (probably will only have a mild speed-up effect)

**Comment by sdrogers** [comment]
Ah, yes, true.

**Comment by oolonek** [comment]
Thanks a lot @sdrogers and @florian-huber for the clarifications ! This was instructive.
I'll go for the cosine calculation then. 

By chance do you know in which aspects is the  NIST MS search different for spectral matching ? 
I just loaded a 300 spectra mgf and basically the library search there is done in less then 10 min ... (similar size of spectral lib, no RT/RI filters ) What could make it quicker here ?

**Comment by sdrogers** [comment]
Afraid not. But I suspect just loads of optimisation for that task. Ie the way spectra is stored in matchms is definitely not the optimal way of storing them if fast similarity computation was your only goal. And things like that can make a lot of difference.

they might also more heavily curate the spectra to remove noise peaks. Reducing number of peaks makes a big difference.

**Comment by hechth** [comment]
@oolonek one difference is also the computation mechanism. NIST defines which spectrum is used for matching peaks (forward/reverse). Matchms uses the intersection, so it looks for matching peaks which is time consuming while I assume that NIST just stores the spectrum as an array where the nominal masses at m/z are the indices, therefore this step isn't necessary. That would be my intuitive response which NIST is so much faster - it is literally just a dot product between vectors while matchms searches for matching peaks.
