### ISSUE TITLE
Add option for progress bars. 

### ISSUE THREAD

**Issue by niekdejonge** [matchms/matchms#366]
Currently calculate_scores does not show any progress bar. 
Since, Scores checks for the type to be List, tuple or np.array. It is also not possible to use tqdm() on the input spectra, since this will be of type tqdm class. 

Proposed changes:
1. Add an option to show progress bars for calculate_scores
2. Change the assert statement in Scores, to checking if it is an iterable, instead of checking if it is List, tuple or np.array

**Comment by florian-huber** [comment]
Duplicate of #164, but totally agree that this would be very nice to have!
In particular the large scale score computations take a lot of time. Unfortunately, those are also not easy to combine with a progress bar because they often consist of numba compiled functions (often a numba function called from another numba function...).

Maybe something along the lines of [numba-progress](https://pypi.org/project/numba-progress/) could work?

**Comment by niekdejonge** [comment]
Numba-progress sounds like a good solution indeed!
