### ISSUE TITLE
Raise minimum python to 3.8?

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#395]
The CI is super slow - resolving the conda dependencies takes about 3h20m on the CI for python 3.7 - do we want to discontinue using the CI for this python version?

**Comment by florian-huber** [comment]
Definitely shouldn't take that long!

Usualy all runs were between 2-11 minutes (e.g. https://github.com/matchms/matchms/actions/runs/4584777969)

If 3.7 indeed becomes that slow I agree we should move to 3.8 and higher.

**Comment by florian-huber** [comment]
Well... I start to experience this myself... seems to be very slow for 3.7.

**Comment by florian-huber** [comment]
Trying out in #402

**Comment by florian-huber** [comment]
Now in parallel trying something else in #403.

@hechth The cond install part indeed started to fail. Some runs with Python 3.7 didn't finish within 5h, so that is clearly not maintainable.
I looked at it again, and the CI part is named misleadingly as "Install conda dependencies" while it actually only installs `rdkit` using conda. `rdkit` is notoriously complicated to handle (when ChatGPT 5 is out I will run an attempt to create a `rdkit-light` 🙄 ).
Anyway, seems it no longer works for us together with Python 3.7.

I am trying 2 things:
- Moving to Python 3.8, 3.9, and 3.10 --> seems to work! (#402)
- Installing rdkit using mamba instead of conda, I anyway wanted to test mamba a bit more since I had a lot of conda issues recently --> seems to work, too. And it makes installing rdkit faster! (#403).

**Comment by florian-huber** [comment]
Now that both options seem to work, my own vote would be to combine both:
- Move to Python 3.8, 3.9, 3.10
- Install rdkit using mamba (in the CI, to save time)

**Comment by florian-huber** [comment]
Wow... just learned (10 month late) that rdkit is finally also on pypi 🥳 .
So we could also skip the conda/mamba thing for the CI.

**Comment by hechth** [comment]
Then let's skip conda and use pypi. Can we then just use python 3.7 to 3.10 and update the CI to install all dependencies using pypi?

**Comment by florian-huber** [comment]
For now I indeed added all 3.7 to 3.10 which works fine (using pypi).
We might at some point reconsider to split the CI into a small first test and a more extensive run (which will not be triggered for each commit), but let's keep this for later.
