### ISSUE TITLE
Save each spectrum (.ms) format 

### ISSUE THREAD

**Issue by anupriyatripathi** [matchms/matchms#459]
Is it possible to load a peak list (MGF / JSON) and save each spectrum entry as a separate (.ms) file? Perhaps this can already be done?

**Comment by hechth** [comment]
@anupriyatripathi there is a galaxy tool implemented for this available [here](https://umsa.cerit-sc.cz/root?tool_id=toolshed.g2.bx.psu.edu/repos/recetox/matchms_split/matchms_split/0.20.0+galaxy0) but it currently only supports msp - you can convert your mgf to msp though and then convert them back to MGF if needed using the [conversion tool](https://umsa.cerit-sc.cz/root?tool_id=toolshed.g2.bx.psu.edu/repos/recetox/matchms_convert/matchms_convert/0.20.0+galaxy0).

Hope this helps! Otherwise you can do this also using the python API, it should be clear from the documentation.

**Comment by hechth** [comment]
@anupriyatripathi did this solve your problem so that this can be closed?

**Comment by anupriyatripathi** [comment]
Yes, I ended up using matchms API to split my large MGF file into individual spectra files. Thank you for following up :)

**Comment by hechth** [comment]
Was the galaxy step too complex or did you just find it more intuitive via the API? Maybe we can also natively support mgf in the future in the Galaxy tools.
