### ISSUE TITLE
Change build system to use poetry

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#464]
Using poetry as a build system and a `pyproject.toml` file might reduce some of the overhead related to dependencies and might make testing and overall setup easier.

**Comment by niekdejonge** [comment]
Looks good. I have no experience with Poetry, but might be a good step. Would the benefit be speed up of running the tests?

**Comment by niekdejonge** [comment]
Regarding the RDKit dependency. The rationale was to have as little large dependencies as possible, so others can use Matchms without depending on large packages, making installing faster, but mostly to reduce the risk of having dependency issues. I think this really is something that is useful since we expect others to build matchsms into other packages. However, RDKit is now used quite a bit throughout matchms. The checks we now do to check if rdkit is installed and the fact that we have to use a different test pipeline for rdkit, makes development slower and the code base less clean, which to me might outweigh the benefit of having less large dependencies. I don't have any clear preference. What do you think @florian-huber ?

**Comment by florian-huber** [comment]
I am fine with poetry as an alternative to the setup.py approach!
