### ISSUE TITLE
Design useful processor default pipelines

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#528]
The `SpectrumProcessor` now has a few defaults such as `minimal`, `basic`, `default`...

But I believe it would be better to make them rather towards specific use cases that (we think) people might have. This can later of course always adapted based on user feedback!

Here a few suggestions:
- `minimal` something like this seems fine to me, only include filters of which we can hardly imagine that someone might not want to run them
- `lcms_non_annotated`
- `lcms_fully_annotated` (this is now `fully_annotated`)
- `gcms_non_annotated` (without precursor-m/z based filters)
- `gcms_fully_annotated`

`basic` and `default` could hence be removed. We could still *set* the default in the class to, say, lcms_non_annotated.

What do you think @niekdejonge @hechth ?

**Comment by niekdejonge** [comment]
Yes I agree. The minimal, basic, default are a bit arbitrary names. I have already made quite some changes in filter order, but have mainly focused on finalizing the fully annotated and ms2deepscore pipelines. I think we can just combine Minimal, Basic and Default into one pipeline called lcms_non_annotated, by removing the 4 inchikey related filters. 

Now in pipeline the default settings are default, both for the reference and the query spectra, we can probably change this to query: lcms_non_annotated and reference: lcms_fully_annotated.

Additional pipelines, we can add once we discover new specific use cases, or leave this up to the user, since it is quite easy to create your own specific filter pipeline.
