### ISSUE TITLE
Consider including option for MSn data

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#550]
This came up in https://github.com/mzmine/biohack23_p15/issues/10

Currently `matchms` focusses on MS/MS data.
The question now is: do we also want to consider handling MS1 and/or MSn (n>2) data?

I cannot really judge yet how frequently this is going to be a thing. In principle, however, MSn data could be very relevant in the context of spectra comparisons and hence sounds like it fits into matchms.

Any thoughts @niekdejonge @justinjjvanderhooft @hechth ?

**Comment by niekdejonge** [comment]
I feel like MSn is currently not used very much by the community. Do you agree @justinjjvanderhooft? Mainly because there is little software and reference libraries. They are now working at MZMine to quickly create large MSn library that might give a boost to working with MSn again. 

An alternative to storing all the MSn data, it is also possible to create a merged spectrum, which basically creates one MS2 spectrum with all the fragments measured in the multiple MSn steps. You lose the information of which MSn step the fragment was formed, but this would allow for direct processing with matchms, without rewriting too much.

**Comment by florian-huber** [comment]
I thought about merging, too.
That would be very easy to implement and would allow people to work in matchms with MSn data.
But on the long-run we might have to adjust the Spectrum class to also store multiple levels of peaks (if people want to use this).

**Comment by niekdejonge** [comment]
Yes I think in the future that could certainly be valuable. The merging is implemented in MZMine already, so it might not even be needed to also implement in mathms.

**Comment by justinjjvanderhooft** [comment]
I tend to agree that for now focusing on MS2 or merged multistage MS/MS spectra is gaining us more return on investment - we could definitively keep this in mind for a future project (and make sure that the current matchms framework does not exclude this option).... It is a chicken-egg situation though, as with more software tools, more MSn measurements may take place.... And @niekdejonge, MATHms sounds interesting as well ;-)
