### ISSUE TITLE
Add filters `require_retentiontime` and `require_retentionindex`

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#585]
These filters would be useful to for example remove entries from a database that don't have retention time or retention index information.

Each filter should be its own function that takes a spectrum and either returns the same spectrum if it has `retention_index` / `retention_time` set to a valid value or None if otherwise.

An example is available [here](https://github.com/matchms/matchms/blob/master/matchms/filtering/metadata_processing/require_precursor_mz.py).

**Comment by niekdejonge** [comment]
@hechth In addition to checking if the field exists I would add a check that it is a valid entry to make it complete. So checking it is an integer or float. And maybe even adding a minimum and maximum retention time, since I think most chemists discard low and high retention times, since this is often noise.
