### ISSUE TITLE
Scores.scores as a sparse matrix

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms#60]
We could save memory by only storing scores that match a user-provided condition.

**Comment by hechth** [comment]
Maybe this issue fits together with #268 and the masking things discussed in #251, as the masking would likely already give you a sparse matrix

**Comment by florian-huber** [comment]
Good point!
We should indeed consider that option for the masking pipeline. We might want to run some tests with realistic use-cases to see which sparse datatype works best (best tradeoff between memory and performance).

**Comment by florian-huber** [comment]
I had a first look. I think datatypes such as `scipy.sparse.csr_matrix` would work nicely in our case.
The memory usage behaves fine: if all elements of an array are filled the matrix will take up 1.5x more memory, but as soon as we have less than 2/3 of the entries filled it will lower memory usage. 
I guess for large comparisons having only 10% or less being filled is realistic which will result in > 7x reduction in memory.

Another advantage of that datatype is that it could probably be implemented nicely together with our numba functions. All entries will be stored as 3 arrays: row-position, column-position, value, which makes it easy to fill with our numby-based loops.
What could also be cool is that we can double the effect by "stacking" different scores. Instead of storing multiple np.arrays for different scores (in the case of a pipline: #268 ) we only have to store multiple `value` arrays of the same size since the row and colum-positions will be the same!

**Comment by hechth** [comment]
@florian-huber this sounds great, thanks so much for investigating! The only question is how the actual score computation then fits in with the sparse matrices or how it has to be updated - I assume implementing a third function called `sparse_matrix` alongside `pair` and `matrix` will be the way to go?

**Comment by florian-huber** [comment]
Yes, indeed that's also what I thought of. I would add a new method - I even picked the same name ;) - to the base class as [sparse_matrix()](https://github.com/matchms/matchms/blob/6d37632388cef998e308202fb59c1ae5165fba66/matchms/similarity/BaseSimilarity.py#L70) (currently this is a dummy and still uses a numpy array).

I am currently prototyping a suitable datatype (`SparseScoreMatrix` of `SparseStackedMatrix`...?) which could internally be used instead of a Numpy array for Scores.scores. My idea right now is to construct something similar to a scipy COO-matrix, but with methods that allow slicing and stacking multiple entries for each x,y coordinate pair.

Idea is to be able to do:
```python
matrix[4, 5, "parentmass_match"]  # => get parentmass-match score at location 4, 5
matrix[4, :, "parentmass_match"]  # => get parentmass-match scores at locations [4, :]

matrix.stack_coo_matrix(coo_score_matrix, name="cosine")
matrix[4, 5, "cosine"]  # => getcosine score at location 4, 5
```

**Comment by hechth** [comment]
@florian-huber I thought about just replacing the actual scores storing with a sparse matrix and just updating the existing indexing function to be the same as it is at the moment.

**Comment by florian-huber** [comment]
I will update this issue in #336 and close this one.
