### ISSUE TITLE
KeyError: 'num peaks'

### ISSUE THREAD

**Issue by LiuBurger** [matchms/matchms#612]
When loading the MoNA-export-Experimental_Spectra.msp，it corrupt at MoNA_0002705，but MoNA_0002705 has the key ’num peaks‘. And when I load MoNA_0002705 alone，it is OK. It‘s quite confusing.
<img width="359" alt="屏幕截图 2024-04-03 100500" src="https://github.com/matchms/matchms/assets/68485539/f17376d1-876c-4f74-9e96-76bfcad3e256">
<img width="738" alt="屏幕截图 2024-04-03 100641" src="https://github.com/matchms/matchms/assets/68485539/8fb0f539-b15f-4f85-84f8-fd1fcfd2d78d">
<img width="134" alt="屏幕截图 2024-04-03 101021" src="https://github.com/matchms/matchms/assets/68485539/c26257cc-bf1a-4be2-a236-8b8893cce66d">

**Comment by MarJakubec** [comment]
I have same error when uploading .msp files generated by mzvault.

**Comment by MarJakubec** [comment]
I figured it out. In my case it was due to long name of compound: 
Name: 2-{[{[5-(4-Amino-2-oxo-1(2H)-pyrimidinyl)-3,4-dihydroxytetrahydro-2-furanyl]methoxy}(hydroxy)phosphoryl]oxy}-4,5-dihydroxy-6-(1,2,3-trihydroxypropyl)tetrahydro-2H-pyran-2-carboxylic acid (non-preferre
d name)

more verbose error would be appreciated.

**Comment by LiuBurger** [comment]
when using the version 0.28.2, the problem did not occur any more.
