### ISSUE TITLE
Parallel loading

### ISSUE THREAD

**Issue by LiuBurger** [matchms/matchms#698]
Some file is quite big，is there a method to **speed up** the matchms.importing.**load_from_mgf** & matchms.exporting.save_as_mgf ？
Such as multi-core processing.

**Comment by florian-huber** [comment]
So far, there is no such method.
I would also assume that multi-processing probably won't help much since the bottleneck is reading/writing from disk (which is slow for line-by-line text files such as mgf).
You could switch to locally work with pickle files which is often orders of magnitude faster.

**Comment by LiuBurger** [comment]
Thank you for answering！
